added a new category of quotes that are travel quotes in the category.json file
shravan20/github-readme-quotes pull request #257
Opened 2023-10-08 14:44 UTC by psqaure11

2023-10-09 04:57 UTC, shravan20 requested changes
PR LGTM, one change suggested

2023-10-09 04:57 UTC, shravan20 commented on customQuotes/category.json
> +  ]}
Add a bnew le
```suggestion
   ]
  }
  
```

2023-10-09 06:36 UTC, psqaure11 commented on customQuotes/category.json
> +  ]}
I have made the necessary changes

2023-10-11 05:41 UTC, psqaure11 commented
Shravan if you have some time Today kindly look into the changes I have made and merge them

2023-10-12 13:42 UTC, shravan20 approved these changes
PR LGTM

2023-10-12 13:43 UTC, merged

2023-10-12 13:43 UTC, shravan20 commented
@psqaure11: Thank you for your contribution