Update quotes.json
shravan20/github-readme-quotes pull request #270
Opened 2023-10-22 14:38 UTC by RS-labhub

Added a new quote

2023-10-22 14:38 UTC, RS-labhub commented
@shravan20 Please review this now.

2023-10-22 15:48 UTC, shravan20 requested changes

2023-10-22 15:53 UTC, RS-labhub commented on customQuotes/quotes.json
> +    ,{
Actually I'm doing it in the github code editor itself. 

My discord username is @rohansrma

It would be very informative if you tell me so...

2023-10-29 01:36 UTC, shravan20 approved these changes

2023-10-29 01:36 UTC, shravan20 commented on customQuotes/quotes.json
> +    ,{
I have resolved it at the moment

2023-10-29 01:37 UTC, merged